### ISSUE TITLE
Graphics adds collisions

### ISSUE THREAD

**Issue by haider8645** [mars-robot-simulation/envire_mars_graphics#2]
Hello,

I noticed that the the envire_mars_graphics checks for the item tag for visual and collision. It creates collisions as well. The collisions are also created in the envire_mars_ode_collision. Is there a reason for this?

https://github.com/mars-robot-simulation/envire_mars_ode_collision/blob/f9f12b0153a2334f62854daeeb9b7f1202d248ad/src/EnvireOdeCollisionPlugins.cpp#L155

and

https://github.com/mars-robot-simulation/envire_mars_graphics/blob/192255dcb18fc8bf6563c2614d74c9e77c16fdda/src/EnvireMarsGraphics.cpp#L340

Could the addition of collisons be removed from this graphics library?

Best,
Haider

**Comment by jliersch** [comment]
EnvireMarsGraphics adds drawObjects for envire geometry items tagged "collision" (cf. https://github.com/mars-robot-simulation/envire_mars_graphics/blob/192255dcb18fc8bf6563c2614d74c9e77c16fdda/src/EnvireMarsGraphics.cpp#L570) but no collision objects. But I concur, that the name of the method in EnvireMarsGraphics could be improved to better communicate this.
